import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { getResume, getFooter, getNavbar } from "@/lib/contentful";
import ThemeProvider from "@/components/ThemeProvider";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Vasanth Athuluri",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const resumeUrl = await getResume();
  const footer = await getFooter();
  const navItems = await getNavbar();

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider>
          <Navbar resumeUrl={resumeUrl} navItems={navItems} />
          {children}
          <Footer footerText={footer?.footerText} linkedIn={footer?.linkedIn} gitHub={footer?.gitHub} />
        </ThemeProvider>
      </body>
    </html>
  );
}
